version: "3.3"
services:
    mongodb:
        image : mongo:3.7
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /data/workdir/dockerdata/mongo/:/data/db
        restart: unless-stopped

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.14
        container_name: elasticsearch
        volumes:
            - /data/workdir/dockerdata/elasticsearch:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        restart: unless-stopped
        # chmor -R 777 /data/workdir/dockerdata 并且要设置 vms limit 
    openrasp:
        depends_on:
            - mongodb
            - elasticsearch
        build: .
        container_name: OpenRASP
        ports:
            - 8086:8086
        restart: always
        command: "/rasp-cloud-2022-01-28/rasp-cloud"
